### ISSUE TITLE
关于catkin_make不成功问题

### ISSUE THREAD

**Issue by lgl-960709** [lee-shun/fixed_wing_formation_control#1]
在编译时显示:vir_sim_leader.hpp:23:10: 中缺失fixed_wing_formation_control/FWstates.h: 头文件以及

switch_fw_mode.hpp:22:10: 中缺失fixed_wing_formation_control/Fw_cmd_mode.h头文件~
感谢

**Comment by lee-shun** [comment]
请完整的将报错信息贴出,

**Comment by lgl-960709** [comment]
在编译时显示:

![2022-03-23 09-37-55屏幕截图](https://user-images.githubusercontent.com/82514690/159605025-72cf4176-a2f0-46ba-8e83-0bb5126df96e.png)
![2022-03-23 09-39-30屏幕截图](https://user-images.githubusercontent.com/82514690/159605030-8c1f2d65-12f0-4080-91d4-14b19470023c.png)
感谢前辈的指导

**Comment by lee-shun** [comment]
我已在主分支中修正:
请参见:
https://github.com/lee-shun/fixed_wing_formation_control/commit/fc21675ea637d94a0bbf95b0d35819fb2de39c50

**Comment by lgl-960709** [comment]
请问我可以拜读一下您的这个代码的论文嘛
应该是我的检索方式有问题,我在知网上找不到&nbsp; 万分感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lee-shun/fixed_wing_formation_control"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月23日(星期三) 晚上9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lee-shun/fixed_wing_formation_control] 关于catkin_make不成功问题 (Issue #1)





 
我已在主分支中修正:
 请参见:
 fc21675

**Comment by lee-shun** [comment]
你好，我的论文归属是北京理工大学。

**Comment by lgl-960709** [comment]
您好 我还想请教一下您如何启动gazebo以及编队程序~`




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lee-shun/fixed_wing_formation_control"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月24日(星期四) 凌晨3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lee-shun/fixed_wing_formation_control] 关于catkin_make不成功问题 (Issue #1)





 
Closed #1.

**Comment by lgl-960709** [comment]
感谢前辈百忙之中抽取宝贵时间修改~~万分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lee-shun/fixed_wing_formation_control"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月23日(星期三) 晚上9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lee-shun/fixed_wing_formation_control] 关于catkin_make不成功问题 (Issue #1)





 
我已在主分支中修正:
 请参见:
 fc21675
